@Test
public
void
testTryCatch
(
)
throws
Exception
{
Factory
factory
=
build
(
ClassWithBodies
.
class
,
CWBStatementTemplate
.
class
)
;
CtClass
<
?
>
cwbClass
=
(
CtClass
<
?
>
)
factory
.
Type
(
)
.
get
(
ClassWithBodies
.
class
)
;
assertEquals
(
2
,
cwbClass
.
getMethods
(
)
.
size
(
)
)
;
CtMethod
<
?
>
method
=
cwbClass
.
getMethod
(
"method2"
)
;
CtBlock
<
?
>
methodBody
=
method
.
getBody
(
)
;
assertTrue
(
methodBody
.
getStatement
(
0
)
instanceof
CtTry
)
;
CtTry
tryStmnt
=
(
CtTry
)
methodBody
.
getStatement
(
0
)
;
checkCtBody
(
tryStmnt
,
"try_body"
,
0
)
;
assertEquals
(
1
,
tryStmnt
.
getCatchers
(
)
.
size
(
)
)
;
assertTrue
(
tryStmnt
.
getCatchers
(
)
.
get
(
0
)
instanceof
CtCatch
)
;
checkCtBody
(
tryStmnt
.
getCatchers
(
)
.
get
(
0
)
,
"catch_body"
,
0
)
;
}
