void
tryCatch
(
)
{
@TestTryRename({"-var2","-var3","-var4"})
int
var1
=
1
;
assertTrue
(
var1
==
1
)
;
try
{
@TestTryRename({"-var1","var3","var4"})
int
var2
=
2
;
assertTrue
(
var1
==
1
)
;
assertTrue
(
var2
==
2
)
;
throw
new
Exception
(
"ex2"
)
;
}
catch
(
@TestTryRename({"-var1","var2","-var4"})
Exception
var3
)
{
@TestTryRename({"-var1","var2","-var3"})
int
var4
=
4
;
assertTrue
(
var1
==
1
)
;
assertTrue
(
var4
==
4
)
;
}
}
