private
static
void
assertFails
(
Runnable
code
)
{
try
{
code
.
run
(
)
;
fail
(
)
;
}
catch
(
Exception
e
)
{
}
}
